from enum import Enum

PARKING_FILTER_TYPE = Enum('PARKING_FILTER_TYPE', 'WHITE_LIST BLACK_LIST NONE')
STATIONAR_FILTER_TYPE = Enum('STATIONAR_FILTER_TYPE', 'WHITE_LIST BLACK_LIST NONE')
DB_LOCATION_FILTER = Enum('DB_LOCATION_FILTER', 'NONE GOOD_LOCATION')
